---
port: 8090
prometheusPort: 9090
configFileName: ".config.yaml"
commentPrefix: "kredik"
webhookSecrets:
#  SecretsManagerConfig:
#    prefix: "kredik-shaw/github"
  SecretsEnvConfig:
    prefix: "GITHUB"
organizations:
  - nhyne
