---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kredik-config
  namespace: kredik-shaw
data:
  config: |
    ---
    port: 8090
    prometheusPort: 9090
    configFileName: ".config.yaml"
    commentPrefix: "kredik"
    webhookSecrets:
      SecretsEnvConfig:
        prefix: "KREDIK_WEBHOOK"
    organizations:
      - nhyne
    imageSubstitutions:
      - nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kredik-shaw
  name: kredik-shaw
  namespace: kredik-shaw
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kredik-shaw
  template:
    metadata:
      labels:
        app: kredik-shaw
    spec:
      containers:
      - name: kredik-shaw
        resources:
          limits:
            memory: 1250M
          requests:
            memory: 1250M
        args:
          - "resources/config.yaml"
        env:
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: github-token
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: github-token
        image: nhyne/github-watcher:0.0.15-SNAPSHOT
        ports:
        - containerPort: 8090
          name: webserver
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: "/opt/docker/resources/"
            readOnly: true
          - name: ssh-key
            mountPath: "/home/rashek/.ssh/"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: kredik-config
            items:
              - key: config
                path: "config.yaml"
        - name: ssh-key
          secret:
            secretName: github-token
            items:
              - key: ssh_key
                path: "id_rsa"
              - key: github_host
                path: "known_hosts"
      serviceAccountName: kredik-shaw
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kredik-shaw
  name: kredik-shaw
  namespace: kredik-shaw
spec:
  ports:
    - port: 8090
      targetPort: 8090
      name: webserver
    - port: 9090
      targetPort: 9090
      name: metrics
  selector:
    app: kredik-shaw
  type: ClusterIP
