apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kredik-shaw
subjects:
  - kind: ServiceAccount
    name: kredik-shaw
    namespace: kredik-shaw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
#  name: kredik-shaw
  name: cluster-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kredik-shaw
  namespace: kredik-shaw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kredik-shaw
rules:
  - verbs: ["create", "update", "delete", "get"]
    resources: ["namespaces"]
    resourceNames: ["pr-*", "watcher-test-*"]
    apiGroups: [""]
