name: "test"
on:
  pull_request:
    branches: "master"
  push:
    branches: "master"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6.3
#       TODO: nix cache fails b/c we do not have a /nix/store dir (or can't write to it)
#      - name: cache nix
#        id: cache-nix
#        uses: actions/cache@v2.1.6
#        with:
#          path: /nix/store
#          key: ${{ runner.os }}-nix-${{ hashFiles('**/*.nix', 'nix/sources.json') }}
      - run: nix-shell --pure --command "scalafmt --non-interactive --check --quiet"
      - run: nix-shell --pure --command "sbt test"
